### ISSUE TITLE
Nice work: Feedback and suggestion.

### ISSUE THREAD

**Issue by TheRealSaiph** [DemonicLaxatives/Bezierio#1]
This is a nice mod, thanks for making it available to the Factorio community. After only a few minutes experimentation using this and the creative mod, I've been able to create and blueprint some nice curved walls to improve the look of my defenses at 90-degree corners.

I have one request/suggestion. Would it be possible to select the building material? Many mods (for example Dectorio) add new materials to Factorio, it would be nice to be able to use them. Of course, the player can change the wall material after the wall is built using the upgrade planner. But it would also be nice to have curved pathways, and the upgrade planner doesn't seem to allow you to switch from a wall entity to a tile entity.

Thanks again, and I hope you'll continue to support and develop this mod in future. I'm looking forward to seeing what features you can come up with!

**Comment by DemonicLaxatives** [comment]
Thank you for your kind words, I'm glad you enjoyed it. I've implemented your suggestion and the update is available on the mod portal. It will not work with all entities and tiles or well with entities larger than 1x1, but should be much better than working with just walls.

**Comment by TheRealSaiph** [comment]
Thanks! I'll try out the new version as soon as I have time.
